name: Build and deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:

jobs:
  build-and-publish:
    if: github.repository_owner == 'PIH'
    concurrency:
      group: build-and-deploy-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/build-and-deploy-to-openmrs-jfrog.yml@main
    with:
      image_name: partnersinhealth/lesotho-emr
      notify_ci_dashboard: true
    secrets: inherit

  deploy:
    if: github.repository_owner == 'PIH'
    needs: build-and-publish
    concurrency:
      group: deploy-to-app-cluster-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/deploy-via-runner.yml@main
    with:
      runner-label: appclstr-01
      notify_ci_dashboard: true
    secrets: inherit
